/* Generated By:JavaCC: Do not edit this line. MeowCompilerLexico.java */
public class MeowCompilerLexico implements MeowCompilerLexicoConstants {
    public static void main(String[] args) throws Exception {
        MeowCompilerLexico lexer = new MeowCompilerLexico(System.in);
        Token token;
        boolean huboErrores = false;
        StringBuilder errores = new StringBuilder();

        while ((token = lexer.getNextToken()).kind != 0) {
            String nombreToken;
                    switch (token.kind) {
                        /* Imprime el par ordenado */
                        // Palabras reservadas
                        case MeowCompilerLexicoConstants.INICIO: nombreToken = "INICIO"; break;
                        case MeowCompilerLexicoConstants.FIN: nombreToken = "FIN"; break;
                        case MeowCompilerLexicoConstants.LEER: nombreToken = "LEER"; break;
                        case MeowCompilerLexicoConstants.IMPRIMIR: nombreToken = "IMPRIMIR"; break;
                        case MeowCompilerLexicoConstants.SI: nombreToken = "SI"; break;
                        case MeowCompilerLexicoConstants.SINO: nombreToken = "SINO"; break;
                        case MeowCompilerLexicoConstants.MIENTRAS: nombreToken = "MIENTRAS"; break;
                        case MeowCompilerLexicoConstants.PARA: nombreToken = "PARA"; break;
                        case MeowCompilerLexicoConstants.OP_ARR: nombreToken = "OP_ARR"; break;
                        case MeowCompilerLexicoConstants.OP_MAT: nombreToken = "OP_MAT"; break;
                        // Operadores incremento / decremento
                        case MeowCompilerLexicoConstants.INCREMENTO: nombreToken = "INCREMENTO"; break;
                        case MeowCompilerLexicoConstants.DECREMENTO: nombreToken = "DECREMENTO"; break;
                        // Operadores aritméticos
                        case MeowCompilerLexicoConstants.SUMA: nombreToken = "SUMA"; break;
                        case MeowCompilerLexicoConstants.RESTA: nombreToken = "RESTA"; break;
                        case MeowCompilerLexicoConstants.MULTIPLICACION: nombreToken = "MULTIPLICACION"; break;
                        case MeowCompilerLexicoConstants.DIVISION: nombreToken = "DIVISION"; break;
                        // Operadores comparación
                        case MeowCompilerLexicoConstants.MENOR: nombreToken = "MENOR"; break;
                        case MeowCompilerLexicoConstants.MAYOR: nombreToken = "MAYOR"; break;
                        case MeowCompilerLexicoConstants.MENOR_IGUAL: nombreToken = "MENOR_IGUAL"; break;
                        case MeowCompilerLexicoConstants.MAYOR_IGUAL: nombreToken = "MAYOR_IGUAL"; break;
                        case MeowCompilerLexicoConstants.IGUAL_COMPARACION: nombreToken = "IGUAL_COMPARACION"; break;
                        case MeowCompilerLexicoConstants.IGUAL_ASIGNACION: nombreToken = "IGUAL_ASIGNACION"; break;
                        case MeowCompilerLexicoConstants.DIFERENTE: nombreToken = "DIFERENTE"; break;
                        // Operadores lógicos
                        case MeowCompilerLexicoConstants.Y_LOGICO: nombreToken = "Y_LOGICO"; break;
                        case MeowCompilerLexicoConstants.O_LOGICO: nombreToken = "O_LOGICO"; break;
                        case MeowCompilerLexicoConstants.NO_LOGICO: nombreToken = "NO_LOGICO"; break;
                        // Delimitadores
                        case MeowCompilerLexicoConstants.ABRIR_LLAVE: nombreToken = "ABRIR_LLAVE"; break;
                        case MeowCompilerLexicoConstants.CERRAR_LLAVE: nombreToken = "CERRAR_LLAVE"; break;
                        case MeowCompilerLexicoConstants.ABRIR_PARENTESIS: nombreToken = "ABRIR_PARENTESIS"; break;
                        case MeowCompilerLexicoConstants.CERRAR_PARENTESIS: nombreToken = "CERRAR_PARENTESIS"; break;
                        case MeowCompilerLexicoConstants.ABRIR_CORCHETE: nombreToken = "ABRIR_CORCHETE"; break;
                        case MeowCompilerLexicoConstants.CERRAR_CORCHETE: nombreToken = "CERRAR_CORCHETE"; break;
                        case MeowCompilerLexicoConstants.DELIMITADOR: nombreToken = "DELIMITADOR"; break;
                        case MeowCompilerLexicoConstants.DOS_PUNTOS: nombreToken = "DOS_PUNTOS"; break;
                        case MeowCompilerLexicoConstants.COMA: nombreToken = "COMA"; break;
                        // Tipos de dato
                        case MeowCompilerLexicoConstants.NUMERO: nombreToken = "NUMERO"; break;
                        case MeowCompilerLexicoConstants.DECIMAL: nombreToken = "DECIMAL"; break;
                        case MeowCompilerLexicoConstants.CARACTER: nombreToken = "CARACTER"; break;
                        case MeowCompilerLexicoConstants.TEXTO: nombreToken = "TEXTO"; break;
                        case MeowCompilerLexicoConstants.BOOLEANO: nombreToken = "BOOLEANO"; break;
                        // ID
                        case MeowCompilerLexicoConstants.ID: nombreToken = "ID"; break;
                        // Constantes
                        case MeowCompilerLexicoConstants.CONSTANTE: nombreToken = "CONSTANTE"; break;
                        // Variables
                        case MeowCompilerLexicoConstants.VARIABLE: nombreToken = "VARIABLE"; break;

                        /* errores */
                        case MeowCompilerLexicoConstants.ERROR_SIMBOLO:
                            huboErrores = true;
                            errores.append("\nError l\u00e9xico en l\u00ednea ").append(token.beginLine)
                                .append(", columna ").append(token.beginColumn).append("\n");
                            errores.append("S\u00edmbolo no v\u00e1lido: '").append(token.image).append("'\n");
                            errores.append("Se esperaba: palabra reservada, identificador, n\u00famero u operador v\u00e1lido.\n");
                            continue;

                        case MeowCompilerLexicoConstants.ERROR_TEXTO:
                            huboErrores = true;
                            errores.append("\nError l\u00e9xico en l\u00ednea ").append(token.beginLine)
                                .append(", columna ").append(token.beginColumn).append("\n");
                            errores.append("Texto sin cerrar con comillas dobles (\").\n");
                            continue;

                        case MeowCompilerLexicoConstants.ERROR_CARACTER:
                            huboErrores = true;
                            errores.append("\nError l\u00e9xico en l\u00ednea ").append(token.beginLine)
                                .append(", columna ").append(token.beginColumn).append("\n");
                            errores.append("Car\u00e1cter sin cerrar con comillas simples (').\n");
                            continue;

                        case MeowCompilerLexicoConstants.ERROR_NUMERO_INVALIDO:
                            huboErrores = true;
                            errores.append("\nError l\u00e9xico en l\u00ednea ").append(token.beginLine)
                                 .append(", columna ").append(token.beginColumn).append("\n");
                            errores.append("El n\u00famero no es v\u00e1lido.\n");
                            continue;

                        case MeowCompilerLexicoConstants.ERROR_IDENTIFICADOR_INVALIDO:
                             huboErrores = true;
                             errores.append("\nError l\u00e9xico en l\u00ednea ").append(token.beginLine)
                                  .append(", columna ").append(token.beginColumn).append("\n");
                             errores.append("Variable no v\u00e1lida: Debe comenzar con una letra.\n");
                             continue;

                        default:
                            nombreToken = MeowCompilerLexicoConstants.tokenImage[token.kind]
                                    .replaceAll("^\"|\"$", "")
                                    .replaceAll("^<|>$", "");
                            break;
                    }
                    System.out.println("TOKEN " + nombreToken + " --> " + token.image);
                }

                if (huboErrores) {
                    System.out.println("\nAN\u00c1LISIS L\u00c9XICO CON ERRORES");
                    System.out.println(errores.toString());
                } else {
                    System.out.println("\nAN\u00c1LISIS L\u00c9XICO EXITOSO");
            }
        }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MeowCompilerLexicoTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }

  /** Constructor with InputStream. */
  public MeowCompilerLexico(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MeowCompilerLexico(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MeowCompilerLexicoTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public MeowCompilerLexico(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MeowCompilerLexicoTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public MeowCompilerLexico(MeowCompilerLexicoTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(MeowCompilerLexicoTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List jj_expentries = new java.util.ArrayList();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[54];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 54; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

    }
