/* Generated By:JavaCC: Do not edit this line. MeowCompilerLexicoConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MeowCompilerLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO = 5;
  /** RegularExpression Id. */
  int INICIO = 6;
  /** RegularExpression Id. */
  int FIN = 7;
  /** RegularExpression Id. */
  int LEER = 8;
  /** RegularExpression Id. */
  int IMPRIMIR = 9;
  /** RegularExpression Id. */
  int SI = 10;
  /** RegularExpression Id. */
  int SINO = 11;
  /** RegularExpression Id. */
  int MIENTRAS = 12;
  /** RegularExpression Id. */
  int PARA = 13;
  /** RegularExpression Id. */
  int OP_ARR = 14;
  /** RegularExpression Id. */
  int OP_MAT = 15;
  /** RegularExpression Id. */
  int INCREMENTO = 16;
  /** RegularExpression Id. */
  int DECREMENTO = 17;
  /** RegularExpression Id. */
  int SUMA = 18;
  /** RegularExpression Id. */
  int RESTA = 19;
  /** RegularExpression Id. */
  int MULTIPLICACION = 20;
  /** RegularExpression Id. */
  int DIVISION = 21;
  /** RegularExpression Id. */
  int MENOR = 22;
  /** RegularExpression Id. */
  int MAYOR = 23;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 24;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 25;
  /** RegularExpression Id. */
  int IGUAL_COMPARACION = 26;
  /** RegularExpression Id. */
  int IGUAL_ASIGNACION = 27;
  /** RegularExpression Id. */
  int DIFERENTE = 28;
  /** RegularExpression Id. */
  int Y_LOGICO = 29;
  /** RegularExpression Id. */
  int O_LOGICO = 30;
  /** RegularExpression Id. */
  int NO_LOGICO = 31;
  /** RegularExpression Id. */
  int ABRIR_LLAVE = 32;
  /** RegularExpression Id. */
  int CERRAR_LLAVE = 33;
  /** RegularExpression Id. */
  int ABRIR_PARENTESIS = 34;
  /** RegularExpression Id. */
  int CERRAR_PARENTESIS = 35;
  /** RegularExpression Id. */
  int ABRIR_CORCHETE = 36;
  /** RegularExpression Id. */
  int CERRAR_CORCHETE = 37;
  /** RegularExpression Id. */
  int DELIMITADOR = 38;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 39;
  /** RegularExpression Id. */
  int COMA = 40;
  /** RegularExpression Id. */
  int NUMERO = 41;
  /** RegularExpression Id. */
  int DECIMAL = 42;
  /** RegularExpression Id. */
  int CARACTER = 43;
  /** RegularExpression Id. */
  int TEXTO = 44;
  /** RegularExpression Id. */
  int BOOLEANO = 45;
  /** RegularExpression Id. */
  int ID = 46;
  /** RegularExpression Id. */
  int CONSTANTE = 47;
  /** RegularExpression Id. */
  int VARIABLE = 48;
  /** RegularExpression Id. */
  int ERROR_TEXTO = 49;
  /** RegularExpression Id. */
  int ERROR_CARACTER = 50;
  /** RegularExpression Id. */
  int ERROR_NUMERO_INVALIDO = 51;
  /** RegularExpression Id. */
  int ERROR_IDENTIFICADOR_INVALIDO = 52;
  /** RegularExpression Id. */
  int ERROR_SIMBOLO = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<COMENTARIO>",
    "\"inicio\"",
    "\"fin\"",
    "\"leer\"",
    "\"imprimir\"",
    "\"si\"",
    "\"sino\"",
    "\"mientras\"",
    "\"para\"",
    "\"arreglo\"",
    "\"matriz\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "<NUMERO>",
    "<DECIMAL>",
    "<CARACTER>",
    "<TEXTO>",
    "<BOOLEANO>",
    "<ID>",
    "<CONSTANTE>",
    "<VARIABLE>",
    "<ERROR_TEXTO>",
    "<ERROR_CARACTER>",
    "<ERROR_NUMERO_INVALIDO>",
    "<ERROR_IDENTIFICADOR_INVALIDO>",
    "<ERROR_SIMBOLO>",
  };

}
